# spring.datasource.url=jdbc:mysql://localhost:3306/batchdb

# spring.datasource.username=root
# spring.jpa.hibernate.ddl-auto=update



spring:
 datasource:
  url: jdbc:mysql://localhost:3306/batchdb
  username: root
  password: root
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    format_sql: true
    
# server.servlet.context-path=/product-app

server:
 servlet:
  context-path: /product-app
# port: 5000
  
  
  


